#bridge-file-version: #10
titleraw @s[scores={speed=0}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 0 §7km/h §a=-"}]}
titleraw @s[scores={speed=1}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 1 §7km/h §a=-"}]}
titleraw @s[scores={speed=2}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 2 §7km/h §a=-"}]}
titleraw @s[scores={speed=3}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 3 §7km/h §a=-"}]}
titleraw @s[scores={speed=4}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 4 §7km/h §a=-"}]}
titleraw @s[scores={speed=5}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 5 §7km/h §a=-"}]}
titleraw @s[scores={speed=6}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 6 §7km/h §a=-"}]}
titleraw @s[scores={speed=7}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 7 §7km/h §a=-"}]}
titleraw @s[scores={speed=8}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 8 §7km/h §a=-"}]}
titleraw @s[scores={speed=9}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 9 §7km/h §a=-"}]}
titleraw @s[scores={speed=10}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 10 §7km/h §a=-"}]}
titleraw @s[scores={speed=11}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 11 §7km/h §a=-"}]}
titleraw @s[scores={speed=12}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 12 §7km/h §a=-"}]}
titleraw @s[scores={speed=13}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 13 §7km/h §a=-"}]}
titleraw @s[scores={speed=14}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 14 §7km/h §a=-"}]}
titleraw @s[scores={speed=15}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 15 §7km/h §a=-"}]}
titleraw @s[scores={speed=16}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 16 §7km/h §a=-"}]}
titleraw @s[scores={speed=17}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 17 §7km/h §a=-"}]}
titleraw @s[scores={speed=18}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 18 §7km/h §a=-"}]}
titleraw @s[scores={speed=19}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 19 §7km/h §a=-"}]}
titleraw @s[scores={speed=20}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 20 §7km/h §a=-"}]}
titleraw @s[scores={speed=21}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 21 §7km/h §a=-"}]}
titleraw @s[scores={speed=22}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 22 §7km/h §a=-"}]}
titleraw @s[scores={speed=23}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 23 §7km/h §a=-"}]}
titleraw @s[scores={speed=24}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 24 §7km/h §a=-"}]}
titleraw @s[scores={speed=25}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 25 §7km/h §a=-"}]}
titleraw @s[scores={speed=26}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 26 §7km/h §a=-"}]}
titleraw @s[scores={speed=27}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 27 §7km/h §a=-"}]}
titleraw @s[scores={speed=28}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 28 §7km/h §a=-"}]}
titleraw @s[scores={speed=29}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 29 §7km/h §a=-"}]}
titleraw @s[scores={speed=30}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 30 §7km/h §a=-"}]}
titleraw @s[scores={speed=31}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 31 §7km/h §a=-"}]}
titleraw @s[scores={speed=32}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 32 §7km/h §a=-"}]}
titleraw @s[scores={speed=33}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 33 §7km/h §a=-"}]}
titleraw @s[scores={speed=34}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 34 §7km/h §a=-"}]}
titleraw @s[scores={speed=35}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 35 §7km/h §a=-"}]}
titleraw @s[scores={speed=36}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 36 §7km/h §a=-"}]}
titleraw @s[scores={speed=37}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 37 §7km/h §a=-"}]}
titleraw @s[scores={speed=38}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 38 §7km/h §a=-"}]}
titleraw @s[scores={speed=39}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 39 §7km/h §a=-"}]}
titleraw @s[scores={speed=40}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 40 §7km/h §a=-"}]}
titleraw @s[scores={speed=41}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 41 §7km/h §a=-"}]}
titleraw @s[scores={speed=42}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 42 §7km/h §a=-"}]}
titleraw @s[scores={speed=43}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 43 §7km/h §a=-"}]}
titleraw @s[scores={speed=44}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 44 §7km/h §a=-"}]}
titleraw @s[scores={speed=45}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 45 §7km/h §a=-"}]}
titleraw @s[scores={speed=46}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 46 §7km/h §a=-"}]}
titleraw @s[scores={speed=47}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 47 §7km/h §a=-"}]}
titleraw @s[scores={speed=48}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 48 §7km/h §a=-"}]}
titleraw @s[scores={speed=49}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 49 §7km/h §a=-"}]}
titleraw @s[scores={speed=40}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 50 §7km/h §a=-"}]}
titleraw @s[scores={speed=51}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 51 §7km/h §a=-"}]}
titleraw @s[scores={speed=52}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 52 §7km/h §a=-"}]}
titleraw @s[scores={speed=53}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 53 §7km/h §a=-"}]}
titleraw @s[scores={speed=54}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 54 §7km/h §a=-"}]}
titleraw @s[scores={speed=55}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 55 §7km/h §a=-"}]}
titleraw @s[scores={speed=56}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 56 §7km/h §a=-"}]}
titleraw @s[scores={speed=57}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 57 §7km/h §a=-"}]}
titleraw @s[scores={speed=58}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 58 §7km/h §a=-"}]}
titleraw @s[scores={speed=59}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 59 §7km/h §a=-"}]}
titleraw @s[scores={speed=50}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 60 §7km/h §a=-"}]}
titleraw @s[scores={speed=61}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 61 §7km/h §a=-"}]}
titleraw @s[scores={speed=62}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 62 §7km/h §a=-"}]}
titleraw @s[scores={speed=63}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 63 §7km/h §a=-"}]}
titleraw @s[scores={speed=64}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 64 §7km/h §a=-"}]}
titleraw @s[scores={speed=65}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 65 §7km/h §a=-"}]}
titleraw @s[scores={speed=66}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 66 §7km/h §a=-"}]}
titleraw @s[scores={speed=67}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 67 §7km/h §a=-"}]}
titleraw @s[scores={speed=68}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 68 §7km/h §a=-"}]}
titleraw @s[scores={speed=69}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 69 §7km/h §a=-"}]}
titleraw @s[scores={speed=70}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 70 §7km/h §a=-"}]}
titleraw @s[scores={speed=71}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 71 §7km/h §a=-"}]}
titleraw @s[scores={speed=72}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 72 §7km/h §a=-"}]}
titleraw @s[scores={speed=73}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 73 §7km/h §a=-"}]}
titleraw @s[scores={speed=74}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 74 §7km/h §a=-"}]}
titleraw @s[scores={speed=75}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 75 §7km/h §a=-"}]}
titleraw @s[scores={speed=76}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 76 §7km/h §a=-"}]}
titleraw @s[scores={speed=77}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 77 §7km/h §a=-"}]}
titleraw @s[scores={speed=78}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 78 §7km/h §a=-"}]}
titleraw @s[scores={speed=79}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 79 §7km/h §a=-"}]}
titleraw @s[scores={speed=80}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 80 §7km/h §a=-"}]}
titleraw @s[scores={speed=81}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 81 §7km/h §a=-"}]}
titleraw @s[scores={speed=82}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 82 §7km/h §a=-"}]}
titleraw @s[scores={speed=83}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 83 §7km/h §a=-"}]}
titleraw @s[scores={speed=84}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 84 §7km/h §a=-"}]}
titleraw @s[scores={speed=85}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 85 §7km/h §a=-"}]}
titleraw @s[scores={speed=86}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 86 §7km/h §a=-"}]}
titleraw @s[scores={speed=87}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 87 §7km/h §a=-"}]}
titleraw @s[scores={speed=88}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 88 §7km/h §a=-"}]}
titleraw @s[scores={speed=89}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 89 §7km/h §a=-"}]}
titleraw @s[scores={speed=90}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 90 §7km/h §a=-"}]}
titleraw @s[scores={speed=91}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 91 §7km/h §a=-"}]}
titleraw @s[scores={speed=92}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 92 §7km/h §a=-"}]}
titleraw @s[scores={speed=93}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 93 §7km/h §a=-"}]}
titleraw @s[scores={speed=94}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 94 §7km/h §a=-"}]}
titleraw @s[scores={speed=95}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 95 §7km/h §a=-"}]}
titleraw @s[scores={speed=96}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 96 §7km/h §a=-"}]}
titleraw @s[scores={speed=97}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 97 §7km/h §a=-"}]}
titleraw @s[scores={speed=98}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 98 §7km/h §a=-"}]}
titleraw @s[scores={speed=99}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 99 §7km/h §a=-"}]}
titleraw @s[scores={speed=90}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 100 §7km/h §a=-"}]}
titleraw @s[scores={speed=101}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 101 §7km/h §a=-"}]}
titleraw @s[scores={speed=102}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 102 §7km/h §a=-"}]}
titleraw @s[scores={speed=103}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 103 §7km/h §a=-"}]}
titleraw @s[scores={speed=104}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 104 §7km/h §a=-"}]}
titleraw @s[scores={speed=105}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 105 §7km/h §a=-"}]}
titleraw @s[scores={speed=106}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 106 §7km/h §a=-"}]}
titleraw @s[scores={speed=107}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 107 §7km/h §a=-"}]}
titleraw @s[scores={speed=108}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 108 §7km/h §a=-"}]}
titleraw @s[scores={speed=109}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 109 §7km/h §a=-"}]}
titleraw @s[scores={speed=110}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 110 §7km/h §a=-"}]}
titleraw @s[scores={speed=111}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 111 §7km/h §a=-"}]}
titleraw @s[scores={speed=112}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 112 §7km/h §a=-"}]}
titleraw @s[scores={speed=113}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 113 §7km/h §a=-"}]}
titleraw @s[scores={speed=114}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 114 §7km/h §a=-"}]}
titleraw @s[scores={speed=115}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 115 §7km/h §a=-"}]}
titleraw @s[scores={speed=116}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 116 §7km/h §a=-"}]}
titleraw @s[scores={speed=117}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 117 §7km/h §a=-"}]}
titleraw @s[scores={speed=118}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 118 §7km/h §a=-"}]}
titleraw @s[scores={speed=119}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 119 §7km/h §a=-"}]}
titleraw @s[scores={speed=120}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 120 §7km/h §a=-"}]}
titleraw @s[scores={speed=121}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 121 §7km/h §a=-"}]}
titleraw @s[scores={speed=122}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 122 §7km/h §a=-"}]}
titleraw @s[scores={speed=123}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 123 §7km/h §a=-"}]}
titleraw @s[scores={speed=124}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 124 §7km/h §a=-"}]}
titleraw @s[scores={speed=125}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 125 §7km/h §a=-"}]}
titleraw @s[scores={speed=126}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 126 §7km/h §a=-"}]}
titleraw @s[scores={speed=127}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 127 §7km/h §a=-"}]}
titleraw @s[scores={speed=128}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 128 §7km/h §a=-"}]}
titleraw @s[scores={speed=129}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 129 §7km/h §a=-"}]}
titleraw @s[scores={speed=130}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 130 §7km/h §a=-"}]}
titleraw @s[scores={speed=131}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 131 §7km/h §a=-"}]}
titleraw @s[scores={speed=132}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 132 §7km/h §a=-"}]}
titleraw @s[scores={speed=133}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 133 §7km/h §a=-"}]}
titleraw @s[scores={speed=134}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 134 §7km/h §a=-"}]}
titleraw @s[scores={speed=135}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 135 §7km/h §a=-"}]}
titleraw @s[scores={speed=136}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 136 §7km/h §a=-"}]}
titleraw @s[scores={speed=137}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 137 §7km/h §a=-"}]}
titleraw @s[scores={speed=138}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 138 §7km/h §a=-"}]}
titleraw @s[scores={speed=139}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 139 §7km/h §a=-"}]}
titleraw @s[scores={speed=140}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 140 §7km/h §a=-"}]}
titleraw @s[scores={speed=141}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 141 §7km/h §a=-"}]}
titleraw @s[scores={speed=142}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 142 §7km/h §a=-"}]}
titleraw @s[scores={speed=143}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 143 §7km/h §a=-"}]}
titleraw @s[scores={speed=144}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 144 §7km/h §a=-"}]}
titleraw @s[scores={speed=145}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 145 §7km/h §a=-"}]}
titleraw @s[scores={speed=146}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 146 §7km/h §a=-"}]}
titleraw @s[scores={speed=147}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 147 §7km/h §a=-"}]}
titleraw @s[scores={speed=148}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 148 §7km/h §a=-"}]}
titleraw @s[scores={speed=149}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 149 §7km/h §a=-"}]}
titleraw @s[scores={speed=150}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 150 §7km/h §a=-"}]}
titleraw @s[scores={speed=151}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 151 §7km/h §a=-"}]}
titleraw @s[scores={speed=152}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 152 §7km/h §a=-"}]}
titleraw @s[scores={speed=153}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 153 §7km/h §a=-"}]}
titleraw @s[scores={speed=154}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 154 §7km/h §a=-"}]}
titleraw @s[scores={speed=155}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 155 §7km/h §a=-"}]}
titleraw @s[scores={speed=156}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 156 §7km/h §a=-"}]}
titleraw @s[scores={speed=157}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 157 §7km/h §a=-"}]}
titleraw @s[scores={speed=158}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 158 §7km/h §a=-"}]}
titleraw @s[scores={speed=159}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 159 §7km/h §a=-"}]}
titleraw @s[scores={speed=160}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 160 §7km/h §a=-"}]}
titleraw @s[scores={speed=161}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 161 §7km/h §a=-"}]}
titleraw @s[scores={speed=162}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 162 §7km/h §a=-"}]}
titleraw @s[scores={speed=163}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 163 §7km/h §a=-"}]}
titleraw @s[scores={speed=164}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 164 §7km/h §a=-"}]}
titleraw @s[scores={speed=165}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 165 §7km/h §a=-"}]}
titleraw @s[scores={speed=166}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 166 §7km/h §a=-"}]}
titleraw @s[scores={speed=167}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 167 §7km/h §a=-"}]}
titleraw @s[scores={speed=168}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 168 §7km/h §a=-"}]}
titleraw @s[scores={speed=169}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 169 §7km/h §a=-"}]}
titleraw @s[scores={speed=170}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 170 §7km/h §a=-"}]}
titleraw @s[scores={speed=171}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 171 §7km/h §a=-"}]}
titleraw @s[scores={speed=172}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 172 §7km/h §a=-"}]}
titleraw @s[scores={speed=173}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 173 §7km/h §a=-"}]}
titleraw @s[scores={speed=174}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 174 §7km/h §a=-"}]}
titleraw @s[scores={speed=175}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 175 §7km/h §a=-"}]}
titleraw @s[scores={speed=176}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 176 §7km/h §a=-"}]}
titleraw @s[scores={speed=177}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 177 §7km/h §a=-"}]}
titleraw @s[scores={speed=178}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 178 §7km/h §a=-"}]}
titleraw @s[scores={speed=179}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 179 §7km/h §a=-"}]}
titleraw @s[scores={speed=180}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 180 §7km/h §a=-"}]}
titleraw @s[scores={speed=181}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 181 §7km/h §a=-"}]}
titleraw @s[scores={speed=182}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 182 §7km/h §a=-"}]}
titleraw @s[scores={speed=183}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 183 §7km/h §a=-"}]}
titleraw @s[scores={speed=184}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 184 §7km/h §a=-"}]}
titleraw @s[scores={speed=185}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 185 §7km/h §a=-"}]}
titleraw @s[scores={speed=186}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 186 §7km/h §a=-"}]}
titleraw @s[scores={speed=187}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 187 §7km/h §a=-"}]}
titleraw @s[scores={speed=188}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 188 §7km/h §a=-"}]}
titleraw @s[scores={speed=189}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 189 §7km/h §a=-"}]}
titleraw @s[scores={speed=190}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 190 §7km/h §a=-"}]}
titleraw @s[scores={speed=191}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 191 §7km/h §a=-"}]}
titleraw @s[scores={speed=192}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 192 §7km/h §a=-"}]}
titleraw @s[scores={speed=193}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 193 §7km/h §a=-"}]}
titleraw @s[scores={speed=194}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 194 §7km/h §a=-"}]}
titleraw @s[scores={speed=195}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 195 §7km/h §a=-"}]}
titleraw @s[scores={speed=196}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 196 §7km/h §a=-"}]}
titleraw @s[scores={speed=197}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 197 §7km/h §a=-"}]}
titleraw @s[scores={speed=198}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 198 §7km/h §a=-"}]}
titleraw @s[scores={speed=199}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 199 §7km/h §a=-"}]}
titleraw @s[scores={speed=200}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 200 §7km/h §a=-"}]}
titleraw @s[scores={speed=201}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 201 §7km/h §a=-"}]}
titleraw @s[scores={speed=202}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 202 §7km/h §a=-"}]}
titleraw @s[scores={speed=203}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 203 §7km/h §a=-"}]}
titleraw @s[scores={speed=204}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 204 §7km/h §a=-"}]}
titleraw @s[scores={speed=205}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 205 §7km/h §a=-"}]}
titleraw @s[scores={speed=206}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 206 §7km/h §a=-"}]}
titleraw @s[scores={speed=207}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 207 §7km/h §a=-"}]}
titleraw @s[scores={speed=208}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 208 §7km/h §a=-"}]}
titleraw @s[scores={speed=209}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 209 §7km/h §a=-"}]}
titleraw @s[scores={speed=210}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 210 §7km/h §a=-"}]}
titleraw @s[scores={speed=211}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 211 §7km/h §a=-"}]}
titleraw @s[scores={speed=212}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 212 §7km/h §a=-"}]}
titleraw @s[scores={speed=213}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 213 §7km/h §a=-"}]}
titleraw @s[scores={speed=214}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 214 §7km/h §a=-"}]}
titleraw @s[scores={speed=215}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 215 §7km/h §a=-"}]}
titleraw @s[scores={speed=216}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 216 §7km/h §a=-"}]}
titleraw @s[scores={speed=217}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 217 §7km/h §a=-"}]}
titleraw @s[scores={speed=218}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 218 §7km/h §a=-"}]}
titleraw @s[scores={speed=219}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 219 §7km/h §a=-"}]}
titleraw @s[scores={speed=220}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 220 §7km/h §a=-"}]}
titleraw @s[scores={speed=221}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 221 §7km/h §a=-"}]}
titleraw @s[scores={speed=222}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 222 §7km/h §a=-"}]}
titleraw @s[scores={speed=223}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 223 §7km/h §a=-"}]}
titleraw @s[scores={speed=224}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 224 §7km/h §a=-"}]}
titleraw @s[scores={speed=225}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 225 §7km/h §a=-"}]}
titleraw @s[scores={speed=226}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 226 §7km/h §a=-"}]}
titleraw @s[scores={speed=227}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 227 §7km/h §a=-"}]}
titleraw @s[scores={speed=228}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 228 §7km/h §a=-"}]}
titleraw @s[scores={speed=229}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 229 §7km/h §a=-"}]}
titleraw @s[scores={speed=230}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 230 §7km/h §a=-"}]}
titleraw @s[scores={speed=231}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 231 §7km/h §a=-"}]}
titleraw @s[scores={speed=232}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 232 §7km/h §a=-"}]}
titleraw @s[scores={speed=233}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 233 §7km/h §a=-"}]}
titleraw @s[scores={speed=234}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 234 §7km/h §a=-"}]}
titleraw @s[scores={speed=235}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 235 §7km/h §a=-"}]}
titleraw @s[scores={speed=236}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 236 §7km/h §a=-"}]}
titleraw @s[scores={speed=237}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 237 §7km/h §a=-"}]}
titleraw @s[scores={speed=238}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 238 §7km/h §a=-"}]}
titleraw @s[scores={speed=239}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 239 §7km/h §a=-"}]}
titleraw @s[scores={speed=240}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 240 §7km/h §a=-"}]}
titleraw @s[scores={speed=241}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 241 §7km/h §a=-"}]}
titleraw @s[scores={speed=242}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 242 §7km/h §a=-"}]}
titleraw @s[scores={speed=243}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 243 §7km/h §a=-"}]}
titleraw @s[scores={speed=244}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 244 §7km/h §a=-"}]}
titleraw @s[scores={speed=245}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 245 §7km/h §a=-"}]}
titleraw @s[scores={speed=246}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 246 §7km/h §a=-"}]}
titleraw @s[scores={speed=247}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 247 §7km/h §a=-"}]}
titleraw @s[scores={speed=248}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 248 §7km/h §a=-"}]}
titleraw @s[scores={speed=249}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 249 §7km/h §a=-"}]}
titleraw @s[scores={speed=250}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 250 §7km/h §a=-"}]}
titleraw @s[scores={speed=251}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 251 §7km/h §a=-"}]}
titleraw @s[scores={speed=252}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 252 §7km/h §a=-"}]}
titleraw @s[scores={speed=253}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 253 §7km/h §a=-"}]}
titleraw @s[scores={speed=254}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 254 §7km/h §a=-"}]}
titleraw @s[scores={speed=255}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 255 §7km/h §a=-"}]}
titleraw @s[scores={speed=256}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 256 §7km/h §a=-"}]}
titleraw @s[scores={speed=257}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 257 §7km/h §a=-"}]}
titleraw @s[scores={speed=258}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 258 §7km/h §a=-"}]}
titleraw @s[scores={speed=259}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 259 §7km/h §a=-"}]}
titleraw @s[scores={speed=260}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 260 §7km/h §a=-"}]}
titleraw @s[scores={speed=261}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 261 §7km/h §a=-"}]}
titleraw @s[scores={speed=262}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 262 §7km/h §a=-"}]}
titleraw @s[scores={speed=263}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 263 §7km/h §a=-"}]}
titleraw @s[scores={speed=264}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 264 §7km/h §a=-"}]}
titleraw @s[scores={speed=265}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 265 §7km/h §a=-"}]}
titleraw @s[scores={speed=266}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 266 §7km/h §a=-"}]}
titleraw @s[scores={speed=267}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 267 §7km/h §a=-"}]}
titleraw @s[scores={speed=268}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 268 §7km/h §a=-"}]}
titleraw @s[scores={speed=269}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 269 §7km/h §a=-"}]}
titleraw @s[scores={speed=270}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 270 §7km/h §a=-"}]}
titleraw @s[scores={speed=271}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 271 §7km/h §a=-"}]}
titleraw @s[scores={speed=272}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 272 §7km/h §a=-"}]}
titleraw @s[scores={speed=273}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 273 §7km/h §a=-"}]}
titleraw @s[scores={speed=274}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 274 §7km/h §a=-"}]}
titleraw @s[scores={speed=275}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 275 §7km/h §a=-"}]}
titleraw @s[scores={speed=276}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 276 §7km/h §a=-"}]}
titleraw @s[scores={speed=277}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 277 §7km/h §a=-"}]}
titleraw @s[scores={speed=278}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 278 §7km/h §a=-"}]}
titleraw @s[scores={speed=279}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 279 §7km/h §a=-"}]}
titleraw @s[scores={speed=280}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 280 §7km/h §a=-"}]}
titleraw @s[scores={speed=281}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 281 §7km/h §a=-"}]}
titleraw @s[scores={speed=282}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 282 §7km/h §a=-"}]}
titleraw @s[scores={speed=283}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 283 §7km/h §a=-"}]}
titleraw @s[scores={speed=284}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 284 §7km/h §a=-"}]}
titleraw @s[scores={speed=285}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 285 §7km/h §a=-"}]}
titleraw @s[scores={speed=286}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 286 §7km/h §a=-"}]}
titleraw @s[scores={speed=287}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 287 §7km/h §a=-"}]}
titleraw @s[scores={speed=288}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 288 §7km/h §a=-"}]}
titleraw @s[scores={speed=289}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 289 §7km/h §a=-"}]}
titleraw @s[scores={speed=290}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 290 §7km/h §a=-"}]}
titleraw @s[scores={speed=291}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 291 §7km/h §a=-"}]}
titleraw @s[scores={speed=292}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 292 §7km/h §a=-"}]}
titleraw @s[scores={speed=293}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 293 §7km/h §a=-"}]}
titleraw @s[scores={speed=294}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 294 §7km/h §a=-"}]}
titleraw @s[scores={speed=295}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 295 §7km/h §a=-"}]}
titleraw @s[scores={speed=296}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 296 §7km/h §a=-"}]}
titleraw @s[scores={speed=297}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 297 §7km/h §a=-"}]}
titleraw @s[scores={speed=298}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 298 §7km/h §a=-"}]}
titleraw @s[scores={speed=299}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 299 §7km/h §a=-"}]}
titleraw @s[scores={speed=300..}] actionbar {"rawtext":[{"translate":"speed.slow"},{"text":"\n§a-=§f 300 §7km/h §a=-"}]}